[ble]
enabled = true

[keyboard]
chip = "nrf52840"
manufacturer = "haobo"
name = "RMK Keyboard"
product_id = 17987
product_name = "RMK Keyboard"
vendor_id = 19531

[layout]
cols = 6
layers = 3
rows = 8
keymap = [ [ [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ] ], [ [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ] ], [ [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ], [ "_", "_", "_", "_", "_", "_" ] ] ]

[light]


[split]
connection = "ble"

[[split.peripheral]]
ble_addr = [ 126, 254, 115, 158, 102, 227 ]
col_offset = 0
cols = 6
input_pins = [ "P0_22", "P0_24", "P1_00", "P0_11" ]
output_pins = [ "P1_11", "P1_13", "P1_15", "P0_02", "P0_29", "P0_31" ]
row_offset = 4
rows = 4

[split.central]
ble_addr = [ 24, 226, 33, 128, 192, 199 ]
col_offset = 0
cols = 6
input_pins = [ "P0_22", "P0_24", "P1_00", "P0_11" ]
output_pins = [ "P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11" ]
row_offset = 0
rows = 4

[storage]