light = {}
storage = {}

[keyboard]
name = "RMK Keyboard"
product_name = "RMK Keyboard"
vendor_id = 19531
product_id = 17987
manufacturer = "haobo"
chip = "nrf52840"

[layout]
rows = 8
cols = 6
layers = 3
keymap = [

  [
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
  ],

  [
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
  ],

  [
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
    [
      "_",
      "_",
      "_",
      "_",
      "_",
      "_",
    ],
  ],


]

[ble]
enabled = true

[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0
ble_addr = [24, 226, 33, 128, 192, 199]
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11"]
output_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11"]

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 0
col_offset = 6
ble_addr = [126, 254, 115, 158, 102, 227]
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11"]
output_pins = ["P1_11", "P1_13", "P1_15", "P0_02", "P0_29", "P0_31"]


[split]
connection = "ble"
