[keyboard]
name = "Akarsh keyboard"
product_name = "RMK Keyboard"
vendor_id = 19531
product_id = 17987
manufacturer = "haobo"
chip = "nrf52840"

[matrix]
input_pins = [ "P0_00", "P0_01", "P0_02", "P0_03" ]
output_pins = [ "P0_05", "P0_06", "P0_07" ]

[layout]
rows = 4
cols = 3
layers = 2
keymap = [ [ [ "Kp7", "Kp8", "Kp9" ], [ "Kp4", "Kp5", "Kp6" ], [ "Kp1", "Kp2", "Kp3" ], [ "Kp0", "MO(1)", "Dot" ] ], [ [ "_", "_", "_" ], [ "_", "_", "_" ], [ "_", "_", "_" ], [ "_", "_", "_" ] ] ]

[light]


[storage]


[ble]
enabled = true