name: Build

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install target
        run: rustup target add thumbv7em-none-eabihf thumbv6m-none-eabi thumbv7em-none-eabi
      - name: Install cargo-make
        run: cargo install --force cargo-make
      - name: Build rmk
        run: cargo build --release
      - name: build uf2 firmware file
        run: cargo make uf2 --release 
      - name: Archive (rmk-firmware)
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: rmk.uf2
